insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (1, 1, 'Brodie', 'Golden Retriever', 19, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (2, 2, 'Keen', 'Labrador', 16, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (3, 3, 'Moore', 'Labrador', 11, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (4, 4, 'Allis', 'Other', 20, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (5, 5, 'Opalina', 'Labrador', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (6, 6, 'Christan', 'Golden Retriever', 16, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (7, 7, 'Jordon', 'Golden Retriever', 14, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (8, 8, 'Burg', 'Labrador', 11, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (9, 9, 'Natal', 'Labrador', 11, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (10, 10, 'Lula', 'Other', 7, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (11, 11, 'Nicole', 'Other', 12, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (12, 12, 'Lowell', 'Golden Retriever', 6, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (13, 13, 'Danya', 'Labrador', 4, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (14, 14, 'Trip', 'Other', 1, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (15, 15, 'Jethro', 'Other', 19, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (16, 16, 'Edmon', 'Other', 12, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (17, 17, 'Arleta', 'Other', 15, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (18, 18, 'Barry', 'Golden Retriever', 1, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (19, 19, 'Dallis', 'Other', 2, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (20, 20, 'Teirtza', 'Other', 1, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (21, 21, 'Aeriela', 'Labrador', 19, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (22, 22, 'Karia', 'Labrador', 5, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (23, 23, 'Zacharias', 'Golden Retriever', 5, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (24, 24, 'Terence', 'Golden Retriever', 13, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (25, 25, 'Gonzales', 'Other', 20, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (26, 26, 'Hallie', 'Other', 19, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (27, 27, 'Patton', 'Labrador', 11, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (28, 28, 'Roseann', 'Labrador', 12, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (29, 29, 'Marsha', 'Other', 14, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (30, 30, 'Darcey', 'Labrador', 7, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (31, 31, 'Annette', 'Labrador', 5, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (32, 32, 'Wood', 'Other', 1, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (33, 33, 'Lia', 'Golden Retriever', 12, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (34, 34, 'Coleman', 'Golden Retriever', 15, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (35, 35, 'Alford', 'Other', 2, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (36, 36, 'Darice', 'Golden Retriever', 17, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (37, 37, 'Francine', 'Golden Retriever', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (38, 38, 'Auberon', 'Golden Retriever', 8, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (39, 39, 'Roxi', 'Golden Retriever', 8, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (40, 40, 'Ericka', 'Golden Retriever', 2, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (41, 41, 'Nicole', 'Labrador', 2, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (42, 42, 'Leola', 'Other', 18, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (43, 43, 'Abbott', 'Labrador', 14, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (44, 44, 'Carce', 'Golden Retriever', 7, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (45, 45, 'Whitaker', 'Golden Retriever', 7, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (46, 46, 'Grissel', 'Other', 6, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (47, 47, 'Chandler', 'Other', 5, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (48, 48, 'Dion', 'Labrador', 15, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (49, 49, 'Rawley', 'Labrador', 2, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (50, 50, 'Abraham', 'Other', 20, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (51, 51, 'Bianca', 'Other', 17, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (52, 52, 'Catherine', 'Labrador', 18, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (53, 53, 'Tonnie', 'Other', 20, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (54, 54, 'Blanca', 'Golden Retriever', 13, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (55, 55, 'Carmita', 'Golden Retriever', 18, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (56, 56, 'Coralyn', 'Golden Retriever', 19, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (57, 57, 'Louise', 'Labrador', 16, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (58, 58, 'Daune', 'Labrador', 12, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (59, 59, 'Fran', 'Golden Retriever', 3, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (60, 60, 'Carlie', 'Other', 15, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (61, 61, 'Ephrayim', 'Other', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (62, 62, 'Georgianna', 'Golden Retriever', 17, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (63, 63, 'Catlee', 'Golden Retriever', 16, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (64, 64, 'Kinnie', 'Other', 3, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (65, 65, 'Aron', 'Golden Retriever', 15, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (66, 66, 'Marcy', 'Golden Retriever', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (67, 67, 'Clareta', 'Labrador', 0, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (68, 68, 'Althea', 'Golden Retriever', 17, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (69, 69, 'Anne-marie', 'Other', 11, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (70, 70, 'Modesta', 'Other', 5, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (71, 71, 'Broderic', 'Golden Retriever', 14, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (72, 72, 'Meir', 'Golden Retriever', 4, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (73, 73, 'Edith', 'Labrador', 13, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (74, 74, 'Melodee', 'Labrador', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (75, 75, 'Naomi', 'Golden Retriever', 16, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (76, 76, 'April', 'Golden Retriever', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (77, 77, 'Jackson', 'Golden Retriever', 2, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (78, 78, 'Jilli', 'Golden Retriever', 7, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (79, 79, 'Domenic', 'Labrador', 20, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (80, 80, 'Obediah', 'Other', 7, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (81, 81, 'Maggi', 'Other', 9, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (82, 82, 'Giselle', 'Golden Retriever', 2, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (83, 83, 'Vincenty', 'Labrador', 2, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (84, 84, 'Heather', 'Other', 15, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (85, 85, 'Melody', 'Other', 14, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (86, 86, 'Blake', 'Golden Retriever', 8, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (87, 87, 'Almeria', 'Labrador', 5, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (88, 88, 'Adriena', 'Other', 9, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (89, 89, 'Amargo', 'Labrador', 15, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (90, 90, 'Taylor', 'Labrador', 19, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (91, 91, 'Stormi', 'Golden Retriever', 9, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (92, 92, 'Tomaso', 'Other', 8, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (93, 93, 'Stanislas', 'Golden Retriever', 0, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (94, 94, 'Ingeberg', 'Labrador', 12, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (95, 95, 'Doyle', 'Golden Retriever', 11, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (96, 96, 'Cyrille', 'Golden Retriever', 0, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (97, 97, 'Harry', 'Golden Retriever', 9, 'Outdated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (98, 98, 'Wilone', 'Other', 15, 'Not vaccinated');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (99, 99, 'Deedee', 'Golden Retriever', 13, 'Up to date');
insert into Dogs (dog_id, client_id, name, breed, age, vaccination_status) values (100, 100, 'Keslie', 'Labrador', 0, 'Up to date');
